project:
  type: website
  output-dir: docs

website:
  title: "SciQuest"
  image: media/blog_preview.png
  favicon: favicon.png
  page-navigation: true
  page-footer:
    left: "Blog made using [Quarto®](https://quarto.org/) with ❤️, by Jewel Johnson."
    right:
      - icon: github
        href: https://github.com/jeweljohnsonj
      - icon: twitter
        href: https://twitter.com/jeweljohnsonj
      - icon: briefcase
        href: mailto:jewel15@alumni.iisertvm.ac.in
      - icon: house
        href: mailto:jeweljohnsonj@gmail.com
  open-graph: true
  site-url: "https://sciquest.netlify.app/"
  repo-url: "https://github.com/jeweljohnsonj/SciQuest"
  repo-actions: [edit, issue]
  twitter-card: true
  google-analytics: G-EVCS615JQR
    
  navbar:
    logo: favicon.png
    right:
      - text: "Blog"
        href: blog.qmd
      - text: "Tutorials"
        href: tutorials.qmd
      - text: "About me"
        href: https://jeweljohnsonj.github.io/jewel_resume/
      - icon: github
        href: https://github.com/jeweljohnsonj/SciQuest
      - icon: twitter
        href: https://twitter.com/jeweljohnsonj
 
format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    toc-title: On this page
    html-math-method: katex
    number-sections: true
    smooth-scroll: true
    highlight-style: github
    code-link: true
    df-print: paged

citation: true

comments:
  giscus:
    repo: jeweljohnsonj/SciQuest

editor: source

freeze: auto

# Extension settings
filters:
   - lightbox
