project:
  type: website
  output-dir: docs
website:
  title: "one-carat-blog"
  sidebar:
  - id: rtutorials
    style: "docked"
    search: true
    contents:
      - section: "Chapters"
        contents:
          - project1.qmd
          - project2.qmd
  navbar:
    right:
      - text: "Blog"
        href: blog.qmd
      - text: "R tutorials"
        menu:
          - text: "Data visualization"
            href: project1.qmd
      - text: "About me"
        href: https://jeweljohnsonj.github.io/jewel_resume/
      - icon: github
        href: https://github.com/jeweljohnsonj/one-carat-blog
      - icon: twitter
        href: https://twitter.com/jeweljohnsonj
format:
  html:
    theme: slate
    css: styles.css

editor: visual

